### ISSUE TITLE
Add Titanic Survival Prediction 

### ISSUE THREAD

**Issue by KilariBinduYadav** [gdsc-gvp/Machine-learning#12]
### Dataset Link
[Dataset](https://www.kaggle.com/c/titanic/data)

### Description
Predicting the survival on Titanic using Machine Learning Algorithms

**Comment by leandronogSS** [comment]
I would like pick up this issue, can you assign it me? 😄

**Comment by Mrdecent08** [comment]
Yeah you can work on it.
