### ISSUE TITLE
Add Breast Cancer Prediction

### ISSUE THREAD

**Issue by KilariBinduYadav** [gdsc-gvp/Machine-learning#13]
### Dataset Link
[Dataset](https://www.kaggle.com/uciml/breast-cancer-wisconsin-data)
### Description
Predicting whether the cancer is mild or deadly

**Comment by tanvideshmukh29** [comment]
Can I work on this issue as a part of hacktoberfest2021.
can you please assign this to me.

**Comment by deephunt3r** [comment]
Yes!
