### ISSUE TITLE
Add Email Spam Classification

### ISSUE THREAD

**Issue by KilariBinduYadav** [gdsc-gvp/Machine-learning#15]
### Dataset Link 
[Dataset](https://www.kaggle.com/venky73/spam-mails-dataset)
### Description
Classifying the emails as spam or not spam

**Comment by tanvideshmukh29** [comment]
Can I work on this issue as a part of hacktoberfest2021.
can you please assign this to me.

**Comment by deephunt3r** [comment]
yes! Assigned
