### ISSUE TITLE
Add Credit Card Fraud Detection

### ISSUE THREAD

**Issue by KilariBinduYadav** [gdsc-gvp/Machine-learning#17]
### Dataset Link 
[Dataset](https://www.kaggle.com/mlg-ulb/creditcardfraud)

### Description
Detecting whether the credit card transactions are fraudulent or not

**Comment by 29riyasaxena** [comment]
Hi @KilariBinduYadav ! I have already worked on this issue. Can you please assign it to me?

**Comment by Mrdecent08** [comment]
Yeah sure 👍 !!
