### ISSUE TITLE
Add wine quality prediction

### ISSUE THREAD

**Issue by Mrdecent08** [gdsc-gvp/Machine-learning#3]
### Description
Prediction of quality of wine based on various factors using regression algorithms.

**Comment by IMvision12** [comment]
I would like to work on this

**Comment by 29riyasaxena** [comment]
Hi! I would like to work on this but the dataset is missing.

**Comment by deephunt3r** [comment]
> Hi! I would like to work on this but the dataset is missing.

Hey! Sorry for that! you can find relevant data set on kaggle I guess!
or @Mrdecent08 will provide it
