### ISSUE TITLE
Add Diabetes Prediction

### ISSUE THREAD

**Issue by Mrdecent08** [gdsc-gvp/Machine-learning#7]
### Dataset Link 
[Dataset](https://www.kaggle.com/johndasilva/diabetes)
### Description
Prediction of Diabetes based on various factors.

**Comment by leandronogSS** [comment]
I would like pick up this issue, can you assign it me? 😄

**Comment by KilariBinduYadav** [comment]
Yes, You can work on it.

**Comment by tanvideshmukh29** [comment]
Can I work on this issue as a part of hacktoberfest2021

**Comment by deephunt3r** [comment]
Sorry! Some one already grabed that issue
