### ISSUE TITLE
Add car price prediction 

### ISSUE THREAD

**Issue by Mrdecent08** [gdsc-gvp/Machine-learning#8]
### Dataset Link 
[Dataset](https://www.kaggle.com/adityadesai13/used-car-dataset-ford-and-mercedes)

### Description
Prediction of car price based on various factors it depends.

**Comment by manjalshah** [comment]
Hello, I am willing to contribute to this issue. Can you please assign it to me?

**Comment by Mrdecent08** [comment]
Sure! 👍
